---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-order-deployment
  labels:
    app: sales-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-order
      version: v1
  template:
    metadata:
      labels:
        app: sales-order
        version: v1
    spec:
      containers:
        - name: sales-order
          image: fofcn/sales-order-v1:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sales-order-service
spec:
  type: ClusterIP
  selector:
    app: sales-order
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080