server:
  port: 8080

spring:
  profiles:
    active: dev

product:
  url: http://sales-product-service:8080
feign:
  client:
    config:
      product:
        connectionTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

database:
  jdbcUrl: jdbc:postgresql://localhost:5432/your_database
  username: postgres
  password: postgres

storage:
  dir: ./