---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sales-order-gateway
spec:
  selector:
    istio: ingressgateway # Use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sales-order-vs
spec:
  hosts:
    - "*" # 对所有请求都进行匹配
  gateways:
    - sales-order-gateway
  http:
    - match:
        - uri:
            prefix: "/sales-order"
      fault:
        delay:
          percentage:
            value: 100.0
          fixedDelay: 7s
      retries:
        attempt: 3
        perTryTimeout: 3s
      route:
        - destination:
            host: sales-order-service
            subset: v0
            port:
              number: 8080
          weight: 80
        - destination:
            host: sales-order-service
            subset: v1
            port:
              number: 8080
          weight: 20
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: sales-order-dr
spec:
  host: sales-order-service
  subsets:
    - name: v0
      labels:
        version: v0
    - name: v1
      labels:
        version: v1
---