apiVersion: v1
kind: Secret
metadata:
  name: database-secret
data:
  username: YWRtaW4=
  password: MTIzNDU2

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod
    env: dev
spec:
  containers:
    - name: my-container
      image: nginx:1.19.10
      ports:
        - containerPort: 80
      volumeMounts:
      - name: demo
        mountPath: "/etc/demo"
        readOnly: true
      env: 
        - name: DB_USERNAME
          valueFrom: 
            secretKeyRef:
              name: database-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
  volumes:
  - name: demo
    secret:
      secretName: database-secret